# Site settings
name: Fares Ibney Yusuf
description: "I believe people are capable of incredible things. if they have the support they need.
<br />I am at my best when I get to provide support, build the structure and advocate for others to achieve their goals. 
This is who I am.
<br />I am a Java developer with more than 12 years of experience, familiar with a various set of tools and technologies. 
I am easy to reach and fun to work with. I take initiative and love investigating problems. 
I love to develop exciting and creative applications."
url: ""


# Delete the lines you don't need
email: fares071@gmail.com
github_username:  faresyusuf
linkedin_username:	faresibneyyusuf
#twitter_username: your_twitter_username_goes_here
#medium_username:  your_medium_username_goes_here
# If you don't have a blog page delete the next line
#blog_url: "/blog"
resume_url:	"https://docs.google.com/document/d/1RpMq4cuiARcHb4KtKqcofZUxs09mL2RH_jKtxt71vOg/edit?usp=sharing"

#toptal 
#"https://www.toptal.com/#unite-only-top-tier-programmers-today"
#toptal_url: "http://www.toptal.com/java#productivity"
toptal_url: "https://www.toptal.com/#unite-only-top-tier-programmers-today"
toptal_resume_url: "https://www.toptal.com/resume/fares-ibney-yusuf#unite-only-top-tier-programmers-today"

avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated 
# automatically whenever you change your GitHub profile picture
# avatar_img_path: "https://avatars2.githubusercontent.com/u/17301305"
avatar_img_path: "https://uploads.toptal.io/user/photo/281231/large_3ff23c31d7cee7386672ecab23c7abd8.jpg"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"

# Build settings
markdown: kramdown
permalink: pretty
